server:
  port: 8084
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    health:
      show-details: always

internal:
  api:
    search-service:
      url: http://search-service:8083/search

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: shopping
      username: shopping-service
      password: Password123!


logging:
  level:
    root: INFO
    com.example.shoppingservice: DEBUG